### ISSUE TITLE
dkron 3.2 renamed `--webhook-url` to `--webhook-endpoint`

### ISSUE THREAD

**Issue by fopina** [surface-security/django-dkron#14]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Related software versions.

x

### Affected resource(s)

x

### Link to debug output

x

### Expected output

x

### Actual output

x

### Steps to reproduce

x

### Additional factoids

We either need to bump the minimum supported version (the default value I suppose, should we document that one as minimum supported version?) and update the flag or add some logic to check dkron version being used to easily handle other changes like this in the future without always forcing app users to upgrade versions (which is sometimes problematic)

### References

https://github.com/distribworks/dkron/commit/5419221b2e62f187eff1d0597d2bb027a33fd93e

https://github.com/surface-security/django-dkron/blob/main/dkron/management/commands/run_dkron.py#L119

**Comment by gsilvapt** [comment]
I tried raising another concern there related to this flag but they ignored me :( https://github.com/distribworks/dkron/issues/1147 Looking at the commit there, seems they ignored me because they were going to deprecate it anyway, but although supported it wasn't working. Anyway, now it's gone for good.

Considering a semantic versioning principal, I think we should pin the maximum version this current installation supports `webhook_url` and then release a major version with the necessary changes, I suppose. But I guess you disagree with this approach based on that last phrase.

Alternatively then, I guess we could release a minor release with an updated `argparser` that has a deprecation warning for this specific flag and with the necessary updated logic, to eventually release another patch that drops support for this flag. Not sure if this helps though.

**Comment by fopina** [comment]
Yes, IMO they messed up on that one. They broke the CLI, which might not be considered an API for semanitic versioning purposes, but it should. At very least, they could have gone supporting both flags.

Anyway, I opened this issue to not forget to open the PR later as I'm currently doing this in my fork:
* extract dkron semver from `DKRON_VERSION`
* small `if` just for this flag in `run_dkron`: if < 3.2 `-url`else `-webhook`

I think for major versions it's a tricky topic whether same package should support multiple or not, but in this case it was released as minor...

Anyway, once I clean it up and open the PR, we can review it better there!
